# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/blang/semver";
    fetch = {
      type = "git";
      url = "https://github.com/blang/semver";
      rev = "2ee87856327ba09384cabd113bc6b5d174e9ec0f";
      sha256 = "13ws259bwcibkclbr82ilhk6zadm63kxklxhk12wayklj8ghhsmy";
    };
  }
  {
    goPackagePath = "github.com/dustin/go-humanize";
    fetch = {
      type = "git";
      url = "https://github.com/dustin/go-humanize";
      rev = "79e699ccd02f240a1f1fbbdcee7e64c1c12e41aa";
      sha256 = "0awfqszgjw8qrdw31v74jnvj1jbp7czhd8aq59j57yyj4hy50fzj";
    };
  }
  {
    goPackagePath = "github.com/flynn/json5";
    fetch = {
      type = "git";
      url = "https://github.com/flynn/json5";
      rev = "7620272ed63390e979cf5882d2fa0506fe2a8db5";
      sha256 = "1l3rqfis8b72mqwm88lx78d0mbdihyamj8cgg2pa5vfbq49cpydf";
    };
  }
  {
    goPackagePath = "github.com/gdamore/encoding";
    fetch = {
      type = "git";
      url = "https://github.com/gdamore/encoding";
      rev = "b23993cbb6353f0e6aa98d0ee318a34728f628b9";
      sha256 = "0d7irqpx2fa9vkxgkhf04yiwazsm10fxh0yk86x5crflhph5fv8a";
    };
  }
  {
    goPackagePath = "github.com/go-errors/errors";
    fetch = {
      type = "git";
      url = "https://github.com/go-errors/errors";
      rev = "8fa88b06e5974e97fbf9899a7f86a344bfd1f105";
      sha256 = "02mvb2clbmfcqb4yclv5zhs4clkk9jxi2hiawsynl5fwmgn0d3xa";
    };
  }
  {
    goPackagePath = "github.com/lucasb-eyer/go-colorful";
    fetch = {
      type = "git";
      url = "https://github.com/lucasb-eyer/go-colorful";
      rev = "951b86a69bbd6463d0e19eff378e6905a746e26a";
      sha256 = "1b19jay3l1fal3pyigy85nmlzj0cnklk0lbmdbf07v6yw1w8xpsl";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-isatty";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-isatty";
      rev = "fc9e8d8ef48496124e79ae0df75490096eccf6fe";
      sha256 = "1r5f9gkavkb1w6sr0qs5kj16706xirl3qnlq3hqpszkw9w27x65a";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-runewidth";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-runewidth";
      rev = "97311d9f7767e3d6f422ea06661bc2c7a19e8a5d";
      sha256 = "0dxlrzn570xl7gb11hjy1v4p3gw3r41yvqhrffgw95ha3q9p50cg";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/go-homedir";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/go-homedir";
      rev = "b8bc1bf767474819792c23f32d8286a45736f1c6";
      sha256 = "13ry4lylalkh4g2vny9cxwvryslzyzwp9r92z0b10idhdq3wad1q";
    };
  }
  {
    goPackagePath = "github.com/sergi/go-diff";
    fetch = {
      type = "git";
      url = "https://github.com/sergi/go-diff";
      rev = "feef008d51ad2b3778f85d387ccf91735543008d";
      sha256 = "1pa41f4jd3ms5yvwah707d22hbgxc21wfvkqnr2r332zyps9f37v";
    };
  }
  {
    goPackagePath = "github.com/yuin/gopher-lua";
    fetch = {
      type = "git";
      url = "https://github.com/yuin/gopher-lua";
      rev = "2243d714d6c94951d8ccca8c851836ff47d401c9";
      sha256 = "1fy9pmi9mwq0vjcvx9mxmks9q1ry8vc0987icy8pz8a3glfp256y";
    };
  }
  {
    goPackagePath = "github.com/zyedidia/clipboard";
    fetch = {
      type = "git";
      url = "https://github.com/zyedidia/clipboard";
      rev = "adacf416cec40266b051e7bc096c52951f2725e9";
      sha256 = "0ciad13r8fmkx9zfbrsfy63ma8a2y13sjjiigyqy31d4kpwcmhbg";
    };
  }
  {
    goPackagePath = "github.com/zyedidia/glob";
    fetch = {
      type = "git";
      url = "https://github.com/zyedidia/glob";
      rev = "dd4023a66dc351ae26e592d21cd133b5b143f3d8";
      sha256 = "1vqw4xbqq6j8p5m7mwxvb448w69vjvgzx0ndsfzdh2cxfirwp3y7";
    };
  }
  {
    goPackagePath = "github.com/zyedidia/tcell";
    fetch = {
      type = "git";
      url = "https://github.com/zyedidia/tcell";
      rev = "7095cc1c7f4173ae48314d80878e9985a0658889";
      sha256 = "0h859md0v7fnjckxkqsd0xzkcd0nb1gs2mbklz20w18n63ldzksa";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "66aacef3dd8a676686c7ae3716979581e8b03c47";
      sha256 = "1dz4ngdicsnl378pdv4fr8p0q83vxdsn8x9lf82nds16mhsxg18x";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "18c65dde6afd36dbc39197ca72008895b8dfbfb6";
      sha256 = "1k241lqdrg54mbr63bp82anxdmxm5qy71445as5yd7ir0ljqykaz";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "eb3733d160e74a9c7e442f435eb3bea458e1d19f";
      sha256 = "1srhvcaa9db3a6xj29mkjr5kg33y71pclrlx4vcwz5m1lgb5c7q6";
    };
  }
  {
    goPackagePath = "layeh.com/gopher-luar";
    fetch = {
      type = "git";
      url = "https://github.com/layeh/gopher-luar";
      rev = "189904aa8849a8bcafbccca9ffd3c49d5c8460c2";
      sha256 = "09m7pdi18jfv7fpmrzkb969wrzwkc40ajprrl7lb3p570xaby9fa";
    };
  }
]

