# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/gdamore/encoding";
    fetch = {
      type = "git";
      url = "https://github.com/gdamore/encoding";
      rev = "b23993cbb6353f0e6aa98d0ee318a34728f628b9";
      sha256 = "0d7irqpx2fa9vkxgkhf04yiwazsm10fxh0yk86x5crflhph5fv8a";
    };
  }
  {
    goPackagePath = "github.com/lucasb-eyer/go-colorful";
    fetch = {
      type = "git";
      url = "https://github.com/lucasb-eyer/go-colorful";
      rev = "231272389856c976b7500c4fffcc52ddf06ff4eb";
      sha256 = "161n224v46mln3swzv0009ffj9fxg2n814l9vqs3zh9dq1dmj0jn";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-runewidth";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-runewidth";
      rev = "97311d9f7767e3d6f422ea06661bc2c7a19e8a5d";
      sha256 = "0dxlrzn570xl7gb11hjy1v4p3gw3r41yvqhrffgw95ha3q9p50cg";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/go-homedir";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/go-homedir";
      rev = "b8bc1bf767474819792c23f32d8286a45736f1c6";
      sha256 = "13ry4lylalkh4g2vny9cxwvryslzyzwp9r92z0b10idhdq3wad1q";
    };
  }
  {
    goPackagePath = "github.com/zyedidia/tcell";
    fetch = {
      type = "git";
      url = "https://github.com/zyedidia/tcell";
      rev = "7095cc1c7f4173ae48314d80878e9985a0658889";
      sha256 = "0h859md0v7fnjckxkqsd0xzkcd0nb1gs2mbklz20w18n63ldzksa";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "bd91bbf73e9a4a801adbfb97133c992678533126";
      sha256 = "0hvwl1x8cc728rbk4n4qwq52jhw7dy1hjdhy4r31qdvsk0ac894d";
    };
  }
]
