[
  users/dermetfan.nix
  users/diemetfan.nix

  profiles/desktop.nix
  profiles/media.nix
  profiles/dev.nix
  profiles/admin.nix
  profiles/office.nix
  profiles/game.nix
  profiles/gui.nix
  profiles/iog.nix

  misc/data.nix
  misc/fonts.nix
  misc/gtk.nix
  misc/pulseaudio-oneshot.nix
  misc/norman.nix
  misc/uhk.nix

  services/picom.nix
  services/dunst.nix
  services/i3-sway/i3.nix
  services/i3-sway/sway.nix
  services/parcellite.nix
  services/xscreensaver.nix
  services/rsibreak.nix

  programs/alacritty.nix
  programs/bat.nix
  programs/broot.nix
  programs/cargo.nix
  programs/elvish.nix
  programs/exa.nix
  programs/fish.nix
  programs/firefox.nix
  programs/geany.nix
  programs/git.nix
  programs/htop.nix
  programs/i3status-rust.nix
  programs/kakoune.nix
  programs/mercurial.nix
  programs/micro.nix
  programs/minecraft.nix
  programs/nano.nix
  programs/networkmanager-dmenu.nix
  programs/nitrogen.nix
  programs/ranger.nix
  programs/ripgrep.nix
  programs/rofi.nix
  programs/shells.nix
  programs/starship.nix
  programs/swappy.nix
  programs/swaylock.nix
  programs/timewarrior.nix
  programs/tmux.nix
  programs/volumeicon.nix
  programs/xpdf.nix
  programs/zsh.nix
]
